// This file is auto-generated by scripts/generate-env.js
// Do not edit manually. Set API_URL in .env file instead.

export const environment = {
  production: false,
  apiUrl: 'https://e-commerce-api-63r3.onrender.com',
};
