const fs = require('fs');
const path = require('path');

// Read .env file
const envPath = path.join(__dirname, '..', '.env');
let apiUrl = 'http://localhost:3000';

if (fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, 'utf8');
  const lines = envContent.split('\n');
  
  for (const line of lines) {
    const trimmedLine = line.trim();
    if (trimmedLine.startsWith('API_URL=') && !trimmedLine.startsWith('#')) {
      const value = trimmedLine.split('=').slice(1).join('=').trim();
      // Remove quotes if present
      apiUrl = value.replace(/^["']|["']$/g, '');
      break;
    }
  }
} else {
  // Try to read from process.env (set by dotenv-cli)
  apiUrl = process.env.API_URL || 'http://localhost:3000';
}

// Generate environment.ts content
const envContent = `// This file is auto-generated by scripts/generate-env.js
// Do not edit manually. Set API_URL in .env file instead.

export const environment = {
    production: false,
    apiUrl: '${apiUrl}',
  };
`;

// Write to environment.ts
const envFile = path.join(__dirname, '..', 'src', 'environments', 'environment.ts');
fs.writeFileSync(envFile, envContent, 'utf8');

console.log(`✓ Generated environment.ts with API_URL: ${apiUrl}`);

